### ISSUE TITLE
first test

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [Jean-Baptiste-Lasselle/envoy-proxy-discovery#1]
* let's go : 
  * a custom config : 

```bash
cat << EOF > ./envoy-custom.yaml
admin:
  address:
    socket_address:
      port_value: 9902
EOF

docker run --rm -it \
      -v $(pwd)/envoy-custom.yaml:/envoy-custom.yaml \
      -p 9903:9902 \
      -p 10000:10000 \
      envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2 \
          -c /envoy-custom.yaml


docker run --name adversaire -itd       -p 9903:9902       -p 10001:10000       envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2
```
* and after that : http://0.0.0.0:10001/ gives me the UI
* other configuration which worked : 

```Yaml
admin:
  address:
    socket_address:
      port_value: 9902
  filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: ingress_http
        access_log:
        - name: envoy.access_loggers.stdout
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
```

```bash
cat << EOF > ./my-envoy-config.yaml
admin:
  address:
    socket_address:
      port_value: 9902
EOF


cat << EOF > ./my-envoy-config2.yaml
admin:
  address:
    socket_address:
      port_value: 9902
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
EOF

# ---------
# --------- VALIDATE CONFIGURATION 1 & 2
# ---
# 
# docker run --rm \
      # -v $(pwd)/my-envoy-config.yaml:/my-envoy-config.yaml \
      # envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2 \
          # --mode validate \
          # -c my-envoy-config.yaml
docker pull envoyproxy/envoy:v1.18-latest
docker run --rm \
      -v $(pwd)/my-envoy-config.yaml:/my-envoy-config.yaml \
      envoyproxy/envoy:v1.18-latest \
          --mode validate \
          -c my-envoy-config.yaml


docker run --rm \
      -v $(pwd)/my-envoy-config2.yaml:/my-envoy-config.yaml \
      envoyproxy/envoy:v1.18-latest \
          --mode validate \
          -c my-envoy-config.yaml


# docker run --rm -it \
      # -v $(pwd)/my-envoy-config.yaml:/my-envoy-config.yaml \
      # -p 9903:9902 \
      # -p 10000:10000 \
      # envoyproxy/envoy-dev:f2906f5ce372814b8e6f688a0e1766703d8b56f2 \
          # -c /envoy-custom.yaml

docker run --name envoyeur -itd \
      -v $(pwd)/my-envoy-config2.yaml:/my-envoy-config.yaml \
      -p 9904:9902 \
      -p 10000:10000 \
      envoyproxy/envoy:v1.18-latest \
          -c /envoy-custom.yaml

curl -iv http://127.0.0.1:9904
```

### Logging of Envoy

* By default Envoy system logs are sent to `/dev/stderr`.
* here is how to customize logs folder / files

```bash
mkdir logs

chmod go+rwx logs/

docker run --rm -it \
      -p 10000:10000 \
      -v $(pwd)/logs:/logs \
      envoyproxy/envoy \
          -c /etc/envoy/envoy.yaml \
          --log-path logs/custom.log
```

* with this `envoy.yaml` conf file : 

```bash
cat << EOF > ./envoy.yaml
static_resources:

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io

  clusters:
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
EOF
```
